--liquibase formatted sql

--changeset anastasia:1
create table sock
(
    id          bigint generated by default as identity primary key,
    cotton_part int,
    color       varchar(255),
    quantity    int
);